In [24]:
import numpy as np
import pandas as pd

In [25]:
test = pd.read_csv('./Results/NaiveResults/Quarterly_9_1_0_LB0.csv')
test

     E413    5968.12    5253.51    5871.68
0    E518  12678.300   8146.470   8354.700
1    E474   3118.330   2239.560   3371.500
2    E829   2159.850   8251.710   6020.870
3    E127   4245.590   3574.170   4591.770
4    E875   4788.880   4222.760   4738.510
5     E20   2288.520   1621.890   5536.190
6    E379   9344.810   3296.910   2773.750
7    E647    396.597    488.585    965.270
8    E283   1299.710   1695.340   1247.680
9     E21   3886.780   4686.450   2570.120
10    E13   8635.940   9223.590   8574.530
11   E405    858.056    820.719   1749.740
12   E723   2437.070   2493.630   2598.350
13   E901   4637.210   4571.420   4751.360
14   E548    607.541    629.360   1888.690
15   E404   1127.510   1145.690   1181.000
16   E606   2573.810   2483.710   3583.310
17   E585   5663.420   6555.760   5356.750
18   E364   8629.770   7168.970  12406.200
19   E204   2934.310   2504.040   2910.940
20    E39   1259.540   1149.800   1578.170
21   E165   4635.670   4833.730   4960.110
22   E792   8417.360   9672.780   9597.400
23   E167   4801.610   6730.220   4641.660
24    E45   8338.770   7526.040  11558.600
25   E491    573.798    577.976    634.258
26   E136   1514.850   7505.620   2833.020
27   E846   5455.340   7259.180   3924.780
28   E806   2127.400   2732.250   2382.340
29   E261    906.183    853.387    761.814
..    ...        ...        ...        ...
425  E811   1929.900   1815.900   2415.760
426  E817   1214.750   1154.880   1160.380
427    E1   6800.730   4428.490   7108.110
428  E150   1004.600    695.512    722.345
429  E466   3593.580   4288.320   4900.060
430  E537   1100.480   1143.090    949.854
431  E335  19163.700   8386.000   8084.830
432  E465    844.391   1009.960   1113.040
433  E856   1272.970    972.704   1485.080
434  E133  10677.500   7212.020  12789.400
435  E543   1684.690   5207.120   9896.260
436  E115  20326.200  10822.100   9113.580
437  E842   3541.610   3364.080   3593.550
438  E272   1204.080    948.799   1000.560
439   E64    256.780    453.012   1131.170
440  E848   9242.120   6191.940   9744.720
441  E164   4832.330   9147.700   6240.510
442  E276   2055.140   1783.140   2794.530
443  E349   2779.260   2653.130   2574.460
444   E78   3273.990   2904.040   4063.270
445  E596   7350.290  10387.400   8234.700
446  E836   8849.200   9973.600  12091.300
447  E665  36502.500  13035.600  10689.800
448   E99   3646.020   3738.900   3406.510
449  E786  15815.000   6957.020   5522.820
450   E25   1883.320   1781.550   1477.310
451  E845   1143.850   2465.210   3980.030
452  E555   4954.270   3457.490   2272.100
453   E33  11248.400  11965.500  12936.500
454  E494   5485.000   5762.380   5934.550

[455 rows x 4 columns]

In [26]:
info = pd.read_csv('sales-info.csv')
info

    SalesID  Brand store and brand
0        E1    1.0      (2.0, 1.0)
1        E2    2.0      (2.0, 2.0)
2        E3    3.0      (2.0, 3.0)
3        E4    4.0      (2.0, 4.0)
4        E5    5.0      (2.0, 5.0)
5        E6    6.0      (2.0, 6.0)
6        E7    7.0      (2.0, 7.0)
7        E8    8.0      (2.0, 8.0)
8        E9    9.0      (2.0, 9.0)
9       E10   10.0     (2.0, 10.0)
10      E11   11.0     (2.0, 11.0)
11      E12    1.0      (5.0, 1.0)
12      E13    2.0      (5.0, 2.0)
13      E14    3.0      (5.0, 3.0)
14      E15    4.0      (5.0, 4.0)
15      E16    5.0      (5.0, 5.0)
16      E17    6.0      (5.0, 6.0)
17      E18    7.0      (5.0, 7.0)
18      E19    8.0      (5.0, 8.0)
19      E20    9.0      (5.0, 9.0)
20      E21   10.0     (5.0, 10.0)
21      E22   11.0     (5.0, 11.0)
22      E23    1.0      (8.0, 1.0)
23      E24    2.0      (8.0, 2.0)
24      E25    3.0      (8.0, 3.0)
25      E26    4.0      (8.0, 4.0)
26      E27    5.0      (8.0, 5.0)
27      E28    6.0      (8.0, 6.0)
28      E29    7.0      (8.0, 7.0)
29      E30    8.0      (8.0, 8.0)
..      ...    ...             ...
883    E884    4.0    (132.0, 4.0)
884    E885    5.0    (132.0, 5.0)
885    E886    6.0    (132.0, 6.0)
886    E887    7.0    (132.0, 7.0)
887    E888    8.0    (132.0, 8.0)
888    E889    9.0    (132.0, 9.0)
889    E890   10.0   (132.0, 10.0)
890    E891   11.0   (132.0, 11.0)
891    E892    1.0    (134.0, 1.0)
892    E893    2.0    (134.0, 2.0)
893    E894    3.0    (134.0, 3.0)
894    E895    4.0    (134.0, 4.0)
895    E896    5.0    (134.0, 5.0)
896    E897    6.0    (134.0, 6.0)
897    E898    7.0    (134.0, 7.0)
898    E899    8.0    (134.0, 8.0)
899    E900    9.0    (134.0, 9.0)
900    E901   10.0   (134.0, 10.0)
901    E902   11.0   (134.0, 11.0)
902    E903    1.0    (137.0, 1.0)
903    E904    2.0    (137.0, 2.0)
904    E905    3.0    (137.0, 3.0)
905    E906    4.0    (137.0, 4.0)
906    E907    5.0    (137.0, 5.0)
907    E908    6.0    (137.0, 6.0)
908    E909    7.0    (137.0, 7.0)
909    E910    8.0    (137.0, 8.0)
910    E911    9.0    (137.0, 9.0)
911    E912   10.0   (137.0, 10.0)
912    E913   11.0   (137.0, 11.0)

[913 rows x 3 columns]

In [27]:
#adjust headings for outputted forecasts
def transformer(outframe): 
    #add current headers as last column
    last_entry = list(outframe.keys())
      #make a new data frame for last col and append it to input df
    append_frame = pd.DataFrame([last_entry], columns=last_entry)
    updated = outframe.append(append_frame, ignore_index=True)
    
    #rename column headings
      #build map of old column headings to their replacement
    rename_map = dict()
    keys = list(outframe.keys())
    for i in range(len(keys)): 
        rename_map[keys[i]] = 'V' + str(i+1)
    rename_map
    
      #modify headers to mirror that of the dataframe
    updated = updated.rename(index=int, columns=rename_map)
    
    return updated

test = transformer(test)
test

       V1        V2        V3        V4
0    E518   12678.3   8146.47    8354.7
1    E474   3118.33   2239.56    3371.5
2    E829   2159.85   8251.71   6020.87
3    E127   4245.59   3574.17   4591.77
4    E875   4788.88   4222.76   4738.51
5     E20   2288.52   1621.89   5536.19
6    E379   9344.81   3296.91   2773.75
7    E647   396.597   488.585    965.27
8    E283   1299.71   1695.34   1247.68
9     E21   3886.78   4686.45   2570.12
10    E13   8635.94   9223.59   8574.53
11   E405   858.056   820.719   1749.74
12   E723   2437.07   2493.63   2598.35
13   E901   4637.21   4571.42   4751.36
14   E548   607.541    629.36   1888.69
15   E404   1127.51   1145.69      1181
16   E606   2573.81   2483.71   3583.31
17   E585   5663.42   6555.76   5356.75
18   E364   8629.77   7168.97   12406.2
19   E204   2934.31   2504.04   2910.94
20    E39   1259.54    1149.8   1578.17
21   E165   4635.67   4833.73   4960.11
22   E792   8417.36   9672.78    9597.4
23   E167   4801.61   6730.22   4641.66
24    E45   8338.77   7526.04   11558.6
25   E491   573.798   577.976   634.258
26   E136   1514.85   7505.62   2833.02
27   E846   5455.34   7259.18   3924.78
28   E806    2127.4   2732.25   2382.34
29   E261   906.183   853.387   761.814
..    ...       ...       ...       ...
426  E817   1214.75   1154.88   1160.38
427    E1   6800.73   4428.49   7108.11
428  E150    1004.6   695.512   722.345
429  E466   3593.58   4288.32   4900.06
430  E537   1100.48   1143.09   949.854
431  E335   19163.7      8386   8084.83
432  E465   844.391   1009.96   1113.04
433  E856   1272.97   972.704   1485.08
434  E133   10677.5   7212.02   12789.4
435  E543   1684.69   5207.12   9896.26
436  E115   20326.2   10822.1   9113.58
437  E842   3541.61   3364.08   3593.55
438  E272   1204.08   948.799   1000.56
439   E64    256.78   453.012   1131.17
440  E848   9242.12   6191.94   9744.72
441  E164   4832.33    9147.7   6240.51
442  E276   2055.14   1783.14   2794.53
443  E349   2779.26   2653.13   2574.46
444   E78   3273.99   2904.04   4063.27
445  E596   7350.29   10387.4    8234.7
446  E836    8849.2    9973.6   12091.3
447  E665   36502.5   13035.6   10689.8
448   E99   3646.02    3738.9   3406.51
449  E786     15815   6957.02   5522.82
450   E25   1883.32   1781.55   1477.31
451  E845   1143.85   2465.21   3980.03
452  E555   4954.27   3457.49    2272.1
453   E33   11248.4   11965.5   12936.5
454  E494      5485   5762.38   5934.55
455  E413   5968.12   5253.51   5871.68

[456 rows x 4 columns]

In [28]:
#create true forecast dataframe
truth = pd.DataFrame(columns=['round', 'store', 'brand', 'week', 'weeks ahead', 'prediction'])
truth

Empty DataFrame
Columns: [round, store, brand, week, weeks ahead, prediction]
Index: []

In [20]:
info.iloc[0]

SalesID                    E1
Brand                       1
store and brand    (2.0, 1.0)
Name: 0, dtype: object

In [29]:
def truth_creator(df): 
    #create new df with appropriate columns
    col_list = ['round', 'store', 'brand', 'week', 'weeks ahead', 'prediction']
    truth = pd.DataFrame(columns=['round', 'store', 'brand', 'week', 'weeks ahead', 'prediction'])
    
    for i, val in test.iterrows(): 
        #get code
        entry_code = val['V1']
        
        #row in info df
        info_row_index = int(entry_code[1:]) - 1
        info_row = info.iloc[info_row_index]
        
        #extract brand and store from info dataframe
        brand = info_row['Brand']
        store_and_brand = info_row['store and brand'][1:]
        store = ''
        for i in store_and_brand:
            if i != ',': 
                store += i
            else: 
                break
        store = int(float(store))
        
        #get week number and number of weeks ahead
        forecasts = ['V2', 'V3', 'V4']
        for x in range(len(forecasts)):
            weeks_ahead = x + 1
            week = 160 + weeks_ahead
            prediction = val[forecasts[x]]
            temp = pd.Series([float('nan'), store, brand, week, weeks_ahead, prediction], index=col_list)
            truth = truth.append(temp, ignore_index=True)
        
    return truth

truth = truth_creator(test)
truth

      round  store  brand   week  weeks ahead prediction
0       NaN   93.0    1.0  161.0          1.0    12678.3
1       NaN   93.0    1.0  162.0          2.0    8146.47
2       NaN   93.0    1.0  163.0          3.0     8354.7
3       NaN   89.0    1.0  161.0          1.0    3118.33
4       NaN   89.0    1.0  162.0          2.0    2239.56
5       NaN   89.0    1.0  163.0          3.0     3371.5
6       NaN  126.0    4.0  161.0          1.0    2159.85
7       NaN  126.0    4.0  162.0          2.0    8251.71
8       NaN  126.0    4.0  163.0          3.0    6020.87
9       NaN   40.0    6.0  161.0          1.0    4245.59
10      NaN   40.0    6.0  162.0          2.0    3574.17
11      NaN   40.0    6.0  163.0          3.0    4591.77
12      NaN  131.0    6.0  161.0          1.0    4788.88
13      NaN  131.0    6.0  162.0          2.0    4222.76
14      NaN  131.0    6.0  163.0          3.0    4738.51
15      NaN    5.0    9.0  161.0          1.0    2288.52
16      NaN    5.0    9.0  162.0          2.0    1621.89
17      NaN    5.0    9.0  163.0          3.0    5536.19
18      NaN   76.0    5.0  161.0          1.0    9344.81
19      NaN   76.0    5.0  162.0          2.0    3296.91
20      NaN   76.0    5.0  163.0          3.0    2773.75
21      NaN  106.0    9.0  161.0          1.0    396.597
22      NaN  106.0    9.0  162.0          2.0    488.585
23      NaN  106.0    9.0  163.0          3.0     965.27
24      NaN   64.0    8.0  161.0          1.0    1299.71
25      NaN   64.0    8.0  162.0          2.0    1695.34
26      NaN   64.0    8.0  163.0          3.0    1247.68
27      NaN    5.0   10.0  161.0          1.0    3886.78
28      NaN    5.0   10.0  162.0          2.0    4686.45
29      NaN    5.0   10.0  163.0          3.0    2570.12
...     ...    ...    ...    ...          ...        ...
1338    NaN  126.0   11.0  161.0          1.0     8849.2
1339    NaN  126.0   11.0  162.0          2.0     9973.6
1340    NaN  126.0   11.0  163.0          3.0    12091.3
1341    NaN  109.0    5.0  161.0          1.0    36502.5
1342    NaN  109.0    5.0  162.0          2.0    13035.6
1343    NaN  109.0    5.0  163.0          3.0    10689.8
1344    NaN   28.0   11.0  161.0          1.0    3646.02
1345    NaN   28.0   11.0  162.0          2.0     3738.9
1346    NaN   28.0   11.0  163.0          3.0    3406.51
1347    NaN  121.0    5.0  161.0          1.0      15815
1348    NaN  121.0    5.0  162.0          2.0    6957.02
1349    NaN  121.0    5.0  163.0          3.0    5522.82
1350    NaN    8.0    3.0  161.0          1.0    1883.32
1351    NaN    8.0    3.0  162.0          2.0    1781.55
1352    NaN    8.0    3.0  163.0          3.0    1477.31
1353    NaN  128.0    9.0  161.0          1.0    1143.85
1354    NaN  128.0    9.0  162.0          2.0    2465.21
1355    NaN  128.0    9.0  163.0          3.0    3980.03
1356    NaN   97.0    5.0  161.0          1.0    4954.27
1357    NaN   97.0    5.0  162.0          2.0    3457.49
1358    NaN   97.0    5.0  163.0          3.0     2272.1
1359    NaN    8.0   11.0  161.0          1.0    11248.4
1360    NaN    8.0   11.0  162.0          2.0    11965.5
1361    NaN    8.0   11.0  163.0          3.0    12936.5
1362    NaN   90.0   10.0  161.0          1.0       5485
1363    NaN   90.0   10.0  162.0          2.0    5762.38
1364    NaN   90.0   10.0  163.0          3.0    5934.55
1365    NaN   80.0    6.0  161.0          1.0    5968.12
1366    NaN   80.0    6.0  162.0          2.0    5253.51
1367    NaN   80.0    6.0  163.0          3.0    5871.68

[1368 rows x 6 columns]